default: &default
  adapter: postgresql
development:
  adapter: postgresql
  host: localhost
  database: townsquare
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
staging:
  adapter: postgresql
  host: ec2-107-22-238-96.compute-1.amazonaws.com
  username: jlqnutnsiqhycq
  password: 1clFnNKjHPd_3OMn6-RYp2OzXW
  database: dc0g7vcuo8mk0b
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
