default: &default
  adapter: postgresql
development:
  adapter: postgresql
  host: localhost
  database: townsquare
  username: postgres
  password: postgres
  pool: 5
  timeout: 5000
staging:
  adapter: postgresql
  host: ec2-54-243-203-87.compute-1.amazonaws.com
  username: hizxozxplmvmlo
  password: 69nDxq5rHOU6y0YCWhk0CdNAZi
  database: d52fbueftefdkn
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
