require File.expand_path("../config/boot.rb", __FILE__)
require "sinatra/activerecord/rake"

desc "API Routes"
task :routes do
  Townsquare::API::V1.routes.each do |api|
    puts "        #{api.request_method.ljust(10)} #{api.path.to_s.ljust(40)} #{api.description}"
  end
end

task :clear_database do

end
